### ISSUE TITLE
Program to know if git tag should be treated as a prerelease

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/mobile-tools#19]
If git tag starts with `v0`, e.g `v0.0.5`, it is a "prerelease" version and GitHub release created from it should be marked as such.

We also want to handle prefixes, such as `comms-v0.0.5`.

Currently it's done in an ugly way in GitHub Actions directly:

```bash
- name: Set version data
  run: |
      tag=${{ github.ref_name }}
      prefix=comms-v
      echo "RELEASE_NOTES=$(link-changelog comms $tag $prefix)" >> $GITHUB_ENV
      # set whether is prerelease
      version=${tag#"$prefix"}
      is_prerelease=false
      if [[ "$version" == 0.* ]]; then
        is_prerelease=true
      fi
      echo "IS_PRERELEASE=$is_prerelease" >> $GITHUB_ENV

- name: Create release
   uses: softprops/action-gh-release@v1
   with:
     name: ${{ github.ref_name }}
     body: ${{ env.RELEASE_NOTES }}
     prerelease: ${{ env.IS_PRERELEASE }}
```

Is there an easy way to do this or should I write a small `is-prerelease` shellscript, similarly to `link-changelog`? cc: @iasiu, @Saancreed

**Comment by Saancreed** [comment]
I don't really see any easier way of doing this. Having a script do this for you gives you the benefit of being able to later add support for, e.g, treating tags like `v1.0.0-alpha.1` as if they were prerelease versions too without the need to update every single workflow yaml. But that's up to you.

(Maybe we could create our own Action for this stuff?)

**Comment by bartekpacia** [comment]
Thanks :)

> Maybe we could create our own Action for this stuff?

I was also thinking about this, but I'm pretty sure it's too early now. But would be great in the future :D

**Comment by bartekpacia** [comment]
Also, I don't really like having to specify `$prefix`:

```
$ tag="comms-v0.0.5"
$ prefix="comms-"
$ link-changelog comms v0.0.5 comms-
https://pub.dev/packages/comms/changelog#005
```

Maybe we could get rid of this as well? Or do you think this is too much _implicitness_?

**Comment by Saancreed** [comment]
No strong opinions here. I guess you can default `prefix` to `"${1}-"` if not specified otherwise via the third argument but it's your tool, do as you prefer :stuck_out_tongue:

**Comment by bartekpacia** [comment]
OK, thanks again for your input. Will try to bake something useful.

> it's your tool

nah nah, it's _our_ tool

![44eggm](https://user-images.githubusercontent.com/40357511/187290381-1bd65630-2d9a-40cd-a6b9-30ea8adb0f22.png)
